/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as EstheticienneIdRouteImport } from './routes/estheticienne.$id'
import { Route as MessagesEstheticianIdRouteImport } from './routes/messages.$estheticianId'
import { Route as ReserverServiceIdRouteImport } from './routes/reserver.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const EstheticienneIdRoute = EstheticienneIdRouteImport.update({
  id: '/estheticienne/$id',
  path: '/estheticienne/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesEstheticianIdRoute = MessagesEstheticianIdRouteImport.update({
  id: '/messages/$estheticianId',
  path: '/messages/$estheticianId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverServiceIdRoute = ReserverServiceIdRouteImport.update({
  id: '/reserver/$serviceId',
  path: '/reserver/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/messages/$estheticianId': typeof MessagesEstheticianIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/messages/$estheticianId': typeof MessagesEstheticianIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/messages/$estheticianId': typeof MessagesEstheticianIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profil'
    | '/reservations'
    | '/estheticienne/$id'
    | '/messages/$estheticianId'
    | '/reserver/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profil'
    | '/reservations'
    | '/estheticienne/$id'
    | '/messages/$estheticianId'
    | '/reserver/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profil'
    | '/reservations'
    | '/estheticienne/$id'
    | '/messages/$estheticianId'
    | '/reserver/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfilRoute: typeof ProfilRoute
  ReservationsRoute: typeof ReservationsRoute
  EstheticienneIdRoute: typeof EstheticienneIdRoute
  MessagesEstheticianIdRoute: typeof MessagesEstheticianIdRoute
  ReserverServiceIdRoute: typeof ReserverServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estheticienne/$id': {
      id: '/estheticienne/$id'
      path: '/estheticienne/$id'
      fullPath: '/estheticienne/$id'
      preLoaderRoute: typeof EstheticienneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$estheticianId': {
      id: '/messages/$estheticianId'
      path: '/messages/$estheticianId'
      fullPath: '/messages/$estheticianId'
      preLoaderRoute: typeof MessagesEstheticianIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$serviceId': {
      id: '/reserver/$serviceId'
      path: '/reserver/$serviceId'
      fullPath: '/reserver/$serviceId'
      preLoaderRoute: typeof ReserverServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfilRoute: ProfilRoute,
  ReservationsRoute: ReservationsRoute,
  EstheticienneIdRoute: EstheticienneIdRoute,
  MessagesEstheticianIdRoute: MessagesEstheticianIdRoute,
  ReserverServiceIdRoute: ReserverServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
