/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as EstheticienneIdRouteImport } from './routes/estheticienne.$id'
import { Route as ReserverServiceIdRouteImport } from './routes/reserver.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const EstheticienneIdRoute = EstheticienneIdRouteImport.update({
  id: '/estheticienne/$id',
  path: '/estheticienne/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverServiceIdRoute = ReserverServiceIdRouteImport.update({
  id: '/reserver/$serviceId',
  path: '/reserver/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reservations': typeof ReservationsRoute
  '/estheticienne/$id': typeof EstheticienneIdRoute
  '/reserver/$serviceId': typeof ReserverServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/reservations' | '/estheticienne/$id' | '/reserver/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reservations' | '/estheticienne/$id' | '/reserver/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/reservations'
    | '/estheticienne/$id'
    | '/reserver/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReservationsRoute: typeof ReservationsRoute
  EstheticienneIdRoute: typeof EstheticienneIdRoute
  ReserverServiceIdRoute: typeof ReserverServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estheticienne/$id': {
      id: '/estheticienne/$id'
      path: '/estheticienne/$id'
      fullPath: '/estheticienne/$id'
      preLoaderRoute: typeof EstheticienneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$serviceId': {
      id: '/reserver/$serviceId'
      path: '/reserver/$serviceId'
      fullPath: '/reserver/$serviceId'
      preLoaderRoute: typeof ReserverServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReservationsRoute: ReservationsRoute,
  EstheticienneIdRoute: EstheticienneIdRoute,
  ReserverServiceIdRoute: ReserverServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
